name: Release uv-monorepo-dependency-plugin

on:
    workflow_dispatch:
        inputs:
            releaseVersion:
                description: "Release version"
                required: true
            developmentVersion:
                description: "Next development version"
                required: true

jobs:
    release:
        runs-on: ubuntu-latest

        steps:
            - name: Import GPG key
              uses: crazy-max/ghaction-import-gpg@v6
              with:
                gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
                passphrase: ${{ secrets.GPG_PRIVATE_KEY_PASSPHRASE }}

            - uses: actions/checkout@v4
              with:
                ref: last-mile-release-fixes

            - name: Install Python # use direct install rather than pyenv for CI for large speed improvement
              uses: actions/setup-python@v5
              with:
                python-version: '3.12.9'

            - name: Install uv
              uses: astral-sh/setup-uv@v5
              with:
                # Install a specific version of uv.
                version: "0.6.10"

            - name: Set up JDK 17
              uses: actions/setup-java@v4
              with:
                  java-version: '17'
                  distribution: 'temurin'
                  cache: maven

            - name: Create settings.xml
              id: create-settings-xml
              run: |
                cat > $HOME/.m2/settings.xml << EOF
                <settings>
                  <servers>
                    <server>
                      <id>central</id>
                      <username>${{ secrets.SONATYPE_CENTRAL_REPO_TOKEN_USER }}</username>
                      <password>${{ secrets.SONATYPE_CENTRAL_REPO_TOKEN_KEY }}</password>
                    </server>
                    <server>
                      <id>pypi</id>
                      <username>${{ secrets.PYPI_USERNAME }}</username>
                      <password>${{ secrets.PYPI_TOKEN }}</password>
                    </server>
                  </servers>
                </settings>
                EOF
                echo "HOME_DIR=$HOME" >> "$GITHUB_OUTPUT"

            - name: Release uv-monorepo-dependency-tool
              run: |                  
                  git config --local user.email "uv-monorepo-dependency-tool-noreply@technologybrewery.org"
                  git config --local user.name "Github Actions"
                  git checkout -b ${{ inputs.releaseVersion }}-release                  
                  mvn -B release:clean release:prepare release:perform -Pcentral-release -DreleaseVersion=${{ inputs.releaseVersion }} -DdevelopmentVersion=${{ inputs.developmentVersion }} -Darguments="-Dhabushu.usePyenv=false"
                  git checkout dev
                  git merge --ff-only release-${{ inputs.releaseVersion }}
                  git push origin dev
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}